/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_maachang_leveldb_jni */

#ifndef _Included_org_maachang_leveldb_jni
#define _Included_org_maachang_leveldb_jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_maachang_leveldb_jni
 * Method:    malloc
 */
JNIEXPORT jlong JNICALL Java_org_maachang_leveldb_jni_malloc
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    realloc
 */
JNIEXPORT jlong JNICALL Java_org_maachang_leveldb_jni_realloc
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    free
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    memset
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_memset
  (JNIEnv *, jclass, jlong, jbyte, jint);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    memcpy
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_memcpy
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    memcmp
 */
JNIEXPORT jint JNICALL Java_org_maachang_leveldb_jni_memcmp
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    getByte
 */
JNIEXPORT jbyte JNICALL Java_org_maachang_leveldb_jni_getByte
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    putByte
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_putByte
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    getBinary
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_getBinary
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    putBinary
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_putBinary
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    putChar
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_putChar
  (JNIEnv *, jclass, jlong, jchar);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    getChar
 */
JNIEXPORT jchar JNICALL Java_org_maachang_leveldb_jni_getChar
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    putShort
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_putShort
  (JNIEnv *, jclass, jlong, jshort);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    getShort
 */
JNIEXPORT jshort JNICALL Java_org_maachang_leveldb_jni_getShort
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    putInt
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_putInt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    getInt
 */
JNIEXPORT jint JNICALL Java_org_maachang_leveldb_jni_getInt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    putLong
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_putLong
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    getLong
 */
JNIEXPORT jlong JNICALL Java_org_maachang_leveldb_jni_getLong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    eq
 */
JNIEXPORT jint JNICALL Java_org_maachang_leveldb_jni_eq
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    snappyMaxCompressedLength
 */
JNIEXPORT jint JNICALL Java_org_maachang_leveldb_jni_snappyMaxCompressedLength
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    snappyCompress
 */
JNIEXPORT jint JNICALL Java_org_maachang_leveldb_jni_snappyCompress
  (JNIEnv *, jclass, jlong, jint, jlong, jintArray);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    snappyDecompress
 */
JNIEXPORT jint JNICALL Java_org_maachang_leveldb_jni_snappyDecompress
  (JNIEnv *, jclass, jlong, jint, jlong, jintArray);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_destroy
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_leveldb_1destroy
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_repair
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_leveldb_1repair
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_open
 */
JNIEXPORT jlong JNICALL Java_org_maachang_leveldb_jni_leveldb_1open
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_close
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_leveldb_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_put
 */
JNIEXPORT jint JNICALL Java_org_maachang_leveldb_jni_leveldb_1put
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jint);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_get
 */
JNIEXPORT jint JNICALL Java_org_maachang_leveldb_jni_leveldb_1get
  (JNIEnv *, jclass, jlong, jlong, jint, jlongArray, jint);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_remove
 */
JNIEXPORT jint JNICALL Java_org_maachang_leveldb_jni_leveldb_1remove
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_property
 */
JNIEXPORT jint JNICALL Java_org_maachang_leveldb_jni_leveldb_1property
  (JNIEnv *, jclass, jlong, jlong, jint, jlongArray, jint);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_iterator
 */
JNIEXPORT jlong JNICALL Java_org_maachang_leveldb_jni_leveldb_1iterator
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_vacuum
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_leveldb_1vacuum
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jint );

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_itr_delete
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_leveldb_1itr_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_itr_first
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_leveldb_1itr_1first
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_itr_last
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_leveldb_1itr_1last
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_itr_seek
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_leveldb_1itr_1seek
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_itr_valid
 */
JNIEXPORT jint JNICALL Java_org_maachang_leveldb_jni_leveldb_1itr_1valid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_itr_next
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_leveldb_1itr_1next
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_itr_before
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_leveldb_1itr_1before
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_itr_key
 */
JNIEXPORT jint JNICALL Java_org_maachang_leveldb_jni_leveldb_1itr_1key
  (JNIEnv *, jclass, jlong, jlongArray, jint);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_itr_value
 */
JNIEXPORT jint JNICALL Java_org_maachang_leveldb_jni_leveldb_1itr_1value
  (JNIEnv *, jclass, jlong, jlongArray, jint);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_wb_create
 */
JNIEXPORT jlong JNICALL Java_org_maachang_leveldb_jni_leveldb_1wb_1create
  (JNIEnv *, jclass);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_wb_create_by_size
 */
JNIEXPORT jlong JNICALL Java_org_maachang_leveldb_jni_leveldb_1wb_1create_1by_1size
  (JNIEnv *, jclass, jint );

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_wb_destroy
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_leveldb_1wb_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_wb_clear_by_size
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_leveldb_1wb_1clear_1by_1size
  (JNIEnv *, jclass, jlong, jint );

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_wb_clear
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_leveldb_1wb_1clear
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_wb_put
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_leveldb_1wb_1put
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jint);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_wb_remove
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_leveldb_1wb_1remove
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_wb_values
 */
JNIEXPORT jlong JNICALL Java_org_maachang_leveldb_jni_leveldb_1wb_1values
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_wb_values_size
 */
JNIEXPORT jint JNICALL Java_org_maachang_leveldb_jni_leveldb_1wb_1values_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_wb_flush
 */
JNIEXPORT jint JNICALL Java_org_maachang_leveldb_jni_leveldb_1wb_1flush
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_ss_create
 */
JNIEXPORT jlong JNICALL Java_org_maachang_leveldb_jni_leveldb_1ss_1create
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_ss_destroy
 */
JNIEXPORT void JNICALL Java_org_maachang_leveldb_jni_leveldb_1ss_1destroy
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_maachang_leveldb_jni
 * Method:    leveldb_ss_iterator
 */
JNIEXPORT jlong JNICALL Java_org_maachang_leveldb_jni_leveldb_1ss_1iterator
  (JNIEnv *, jclass, jlong, jlong);


#ifdef __cplusplus
}
#endif
#endif
